export const FetchingGames = 'fetchGames'
export const FetchingCategories = 'fetchCategories'
export const FetchingGame = 'fetchGame'
export const FetchingCategory = 'fetchCategory'
export const FetchingUser = 'fetchUser'